describe('My second test',function(){
    it('test login success',()=>{
        cy.visit('http://localhost:3000/')
        cy.get('#signIn').should('contain','登录').click()
        cy.url().should('eq','http://localhost:3000/SignUp')
        cy.get('#normal_login_username').type('wy122963')
            .should('have.value','wy122963')
        cy.get('#normal_login_password').type('wy13278649176')
            .should('have.value','wy13278649176')
        cy.get('.ant-btn.login-form-button')
            .should('have.attr','type','submit')
            .click()
        cy.url().should('eq','http://localhost:3000/')
        cy.get('#username').should('contain','Hi,')
            .wait(3000)
    })
    it('test login failure',()=>{
        cy.visit('http://localhost:3000/')
        cy.get('#signIn').should('contain','登录').click()
        cy.get('#normal_login_username').type('123456')
            .should('have.value','123456')
        cy.get('#normal_login_password').type('wy13278649176')
            .should('have.value','wy13278649176')
        cy.get('.ant-btn.login-form-button')
            .should('have.attr','type','submit')
            .click()
        cy.get('#normal_login_username')
            .should('have.value','123456')
        cy.get('#normal_login_password')
            .should('have.value','wy13278649176')
    })
})
