describe('My First Test', function() {

  it('Test visit', function() {
    cy.visit('http://localhost:3000/')
  })
  it('test accurate search and update pages',()=>{
    cy.get('.ant-input').should('have.attr','placeholder','输入词条')
        .type('肺气肿').should('have.value','肺气肿')
    cy.get('.ant-btn.ant-input-search-button').should('have.attr','type','button')
        .click()
    cy.url().should('contain','Details')
    cy.get('.bk-title.bk-font36').should('contain','肺气肿')
    cy.get('.title-edit').click()
    cy.url().should("eq",'http://localhost:3000/UpdateEntryDetail')
    cy.get('#nest-messages_name').should('contain','肺气肿')
    cy.get('.ant-input').should('have.attr','placeholder','输入词条').first()
        .type('心脏病').should('have.value','心脏病')
    cy.get('.ant-input-suffix')
        .click()
    cy.url().should('contain','Details')
    cy.get('.bk-title.bk-font36').should('contain','心脏病')
  })
  it("Test fuzzy search",()=>{
    cy.visit('http://localhost:3000/')
    cy.get('.ant-input').should('have.attr','placeholder','输入词条')
        .type('心脏').should('have.value','心脏')
    cy.get('.ant-btn.ant-input-search-button').should('have.attr','type','button')
        .click()
    cy.get('#穿透性心脏外伤').should('contain','穿透性心脏外伤')
        .click()
    cy.url().should('contain','Details')
    cy.get('.bk-title.bk-font36').should('contain','穿透性心脏外伤')
    cy.visit('http://localhost:3000/')
    cy.get('.ant-input').should('have.attr','placeholder','输入词条')
        .type('血管').should('have.value','血管')
    cy.get('.ant-btn.ant-input-search-button').should('have.attr','type','button')
        .click()
    cy.get('#see_all').should('contain','查看全部')
        .click()
    cy.get('#骨血管瘤').should('contain','骨血管瘤')
        .click()
    cy.url().should('contain','Details')
    cy.get('.bk-title.bk-font36').should('contain','骨血管瘤')

  })

})
